(() => {
  const key='claircrm-billing-v1', euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
  let docs=JSON.parse(localStorage.getItem(key))||[{id:1,type:'Devis',number:'DEV-2026-001',client:'Studio M.',title:'Refonte site vitrine',amount:4800,status:'À envoyer'},{id:2,type:'Facture',number:'FAC-2026-001',client:'Atelier Nord',title:'Accompagnement SEO',amount:3200,status:'En attente'}];
  const save=()=>localStorage.setItem(key,JSON.stringify(docs));
  const rows=(list,quote)=>list.map(d=>`<div class="billing-row"><div><strong>${d.number} · ${d.client}</strong><small>${d.title}</small></div><div><strong>${euro(d.amount)}</strong><small class="invoice-status">${d.status}</small></div><button class="secondary bill-action" ${quote?`data-convert="${d.id}"`:`data-paid="${d.id}"`}>${quote?'Facturer':d.status==='Réglée'?'Réglée':'Marquer réglée'}</button></div>`).join('')||'<div class="empty">Aucun document.</div>';
  function render(){const quotes=docs.filter(d=>d.type==='Devis'),invoices=docs.filter(d=>d.type==='Facture'),due=invoices.filter(d=>d.status==='En attente').reduce((s,d)=>s+d.amount,0);billing.innerHTML=`<div class="section-head"><div><p class="label">GESTION FINANCIÈRE</p><h2>Devis & facturation</h2></div><button class="primary" id="newQuote">+ Nouveau devis</button></div><div class="billing-metrics"><div class="metric"><p>Devis en cours</p><strong>${quotes.length}</strong></div><div class="metric"><p>À encaisser</p><strong>${euro(due)}</strong></div><div class="metric"><p>Factures réglées</p><strong>${invoices.filter(d=>d.status==='Réglée').length}</strong></div></div><div class="billing-grid"><article class="panel"><div class="panel-head"><div><p class="label">DEVIS</p><h3>Propositions commerciales</h3></div></div>${rows(quotes,true)}</article><article class="panel"><div class="panel-head"><div><p class="label">FACTURES</p><h3>Suivi des règlements</h3></div></div>${rows(invoices,false)}</article></div>`}
  function form(){const d=document.createElement('dialog');d.innerHTML=`<form><div class="dialog-head"><h2>Nouveau devis</h2><button type="button" class="close">×</button></div><div class="form-fields"><label>Client<input name="client" required></label><label>Objet<input name="title" required></label><label>Montant HT (€)<input name="amount" type="number" required></label></div><div class="form-actions"><button type="button" class="secondary">Annuler</button><button class="primary">Créer</button></div></form>`;document.body.append(d);d.showModal();d.querySelectorAll('[type="button"]').forEach(b=>b.onclick=()=>d.close());d.addEventListener('close',()=>d.remove());d.querySelector('form').onsubmit=e=>{e.preventDefault();let x=Object.fromEntries(new FormData(e.target));docs.push({...x,id:Date.now(),type:'Devis',number:`DEV-2026-${String(docs.filter(d=>d.type==='Devis').length+1).padStart(3,'0')}`,amount:Number(x.amount),status:'À envoyer'});save();d.close();render()}}
  document.addEventListener('click',e=>{if(e.target.id==='newQuote')form();let x=e.target.closest('[data-convert]');if(x){let q=docs.find(d=>d.id==x.dataset.convert);docs.push({...q,id:Date.now(),type:'Facture',number:`FAC-2026-${String(docs.filter(d=>d.type==='Facture').length+1).padStart(3,'0')}`,status:'En attente'});q.status='Facturé';save();render()}x=e.target.closest('[data-paid]');if(x){docs.find(d=>d.id==x.dataset.paid).status='Réglée';save();render()}});
  const billing=document.createElement('section');billing.id='billing';billing.className='view';document.querySelector('main').insertBefore(billing,document.getElementById('tasks'));render();
})();
